import {chromium} from 'playwright';
const br=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});
const p=await br.newPage({viewport:{width:400,height:860}});
let pass=0,fail=0;const ok=(n,c)=>{c?pass++:fail++;console.log(`${c?'PASS':'FAIL'}  ${n}`)};
p.on('pageerror',e=>{fail++;console.log('FAIL JS ERROR '+e.message)});
await p.addInitScript(()=>{speechSynthesis.speak=()=>{};speechSynthesis.cancel=()=>{}});
await p.goto('file:///home/user/Widget/landing.html');
ok('empty state shown first', await p.isVisible('text=Your dictionary starts empty'));
await p.click('mark >> nth=0'); await p.waitForTimeout(400);
ok('tapping a word collects it', await p.isVisible('text=a soft whispering'));
ok('empty state replaced', !(await p.isVisible('text=starts empty')));
ok('shows "in your words"', await p.isVisible('text=Like wind through paper'));
await p.click('mark >> nth=1'); await p.click('mark >> nth=2'); await p.waitForTimeout(400);
ok('collects all three', (await p.locator('.slip').count())===3);
await p.click('mark >> nth=0'); await p.waitForTimeout(200);
ok('no duplicate on re-tap', (await p.locator('.slip').count())===3);
await p.click('.sw[data-v=ember]'); await p.waitForTimeout(300);
ok('vibe switch repaints page', await p.evaluate(()=>document.documentElement.dataset.v)==='ember');
const acc=await p.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--accent').trim());
ok('accent actually changed ('+acc+')', acc==='#ed6b32');
await p.click('#fc'); await p.waitForTimeout(700);
ok('flashcard flips', await p.evaluate(()=>document.getElementById('fc').classList.contains('flipped')));
await p.click('.pills button >> nth=1'); await p.waitForTimeout(400);
ok('rating unflips', !(await p.evaluate(()=>document.getElementById('fc').classList.contains('flipped'))));
await p.click('.toggle'); await p.waitForTimeout(700);
const lum=await p.evaluate(()=>{const c=document.createElement('canvas').getContext('2d');
  c.fillStyle=getComputedStyle(document.body).backgroundColor;const n=parseInt(c.fillStyle.slice(1),16);
  return ((n>>16&255)*.299+(n>>8&255)*.587+(n&255)*.114)/255});
ok('dark theme genuinely dark', lum<0.2);
ok('no horizontal scroll', await p.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
await p.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));
await p.waitForTimeout(900);
ok('scroll reveals fire', await p.evaluate(()=>[...document.querySelectorAll('.reveal')].every(e=>e.classList.contains('in'))));
ok('CTA links to the app', await p.getAttribute('.big','href')==='./index.html');
await p.click('.toggle'); await p.waitForTimeout(600);
await p.evaluate(()=>window.scrollTo(0,0)); await p.waitForTimeout(400);
await p.screenshot({path:'land-top.png'});
await p.evaluate(()=>window.scrollTo(0,900)); await p.waitForTimeout(500);
await p.screenshot({path:'land-mid.png'});
// desktop
const d=await br.newPage({viewport:{width:1000,height:800}});
await d.goto('file:///home/user/Widget/landing.html'); await d.waitForTimeout(600);
console.log('desktop no h-scroll:', await d.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
console.log(`\nPASSED ${pass}  FAILED ${fail}`);
await br.close();
