import {chromium} from 'playwright';
const br=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});
const p=await br.newPage({viewport:{width:400,height:880}});
let pass=0,fail=0;const ok=(n,c)=>{c?pass++:fail++;console.log(`${c?'PASS':'FAIL'}  ${n}`)};
p.on('pageerror',e=>{fail++;console.log('FAIL JS ERROR '+e.message)});
await p.addInitScript(()=>{speechSynthesis.speak=()=>{};speechSynthesis.cancel=()=>{}});
await p.goto('file:///home/user/Widget/index.html');
ok('empty state shown first', await p.isVisible('text=Your dictionary starts empty'));
await p.click('mark >> nth=0'); await p.waitForTimeout(400);
ok('tapping a word collects it', await p.isVisible('text=a soft whispering'));
await p.click('mark >> nth=1'); await p.click('mark >> nth=2'); await p.waitForTimeout(300);
ok('collects all three', (await p.locator('.slip').count())===3);
await p.evaluate(()=>document.querySelector('#sw').scrollIntoView()); await p.waitForTimeout(600);
ok('eight genres offered, not six palettes', (await p.locator('.sw').count())===8);
const names=await p.$$eval('.sw span',e=>e.map(x=>x.textContent));
ok('named by genre '+JSON.stringify(names.slice(0,4)), names.includes('Romance')&&names.includes('Thriller')&&names.includes('Horror'));
ok('no old palette names', !names.includes('Paper')&&!names.includes('Blush'));
ok('weather canvas present', await p.isVisible('#sky'));
ok('weather is running', await p.evaluate(()=>parts.length>0));
ok('literary is the default world', await p.evaluate(()=>document.documentElement.dataset.v)==='literary');
ok('atmosphere line shown', (await p.textContent('#gline')).includes('Dust in a shaft'));
await p.click('.sw[data-v=romance]'); await p.waitForTimeout(500);
ok('romance switches palette', await p.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--accent').trim())==='#e11d6b');
ok('romance switches weather to petals', await p.evaluate(()=>kind)==='petal');
ok('romance line updates', (await p.textContent('#gline')).includes('someone worth the trouble'));
await p.click('.sw[data-v=thriller]'); await p.waitForTimeout(500);
ok('thriller brings rain', await p.evaluate(()=>kind)==='rain');
await p.click('.sw[data-v=horror]'); await p.waitForTimeout(500);
ok('horror brings fog', await p.evaluate(()=>kind)==='fog');
ok('particles actually drift', await p.evaluate(async()=>{const a=parts[0].y;await new Promise(r=>setTimeout(r,400));return parts.length&&parts[0].y!==a}));
await p.click('#fc'); await p.waitForTimeout(700);
ok('flashcard still flips', await p.evaluate(()=>document.getElementById('fc').classList.contains('flipped')));
await p.click('.toggle'); await p.waitForTimeout(700);
const lum=await p.evaluate(()=>{const c=document.createElement('canvas').getContext('2d');
  c.fillStyle=getComputedStyle(document.body).backgroundColor;const n=parseInt(c.fillStyle.slice(1),16);
  return ((n>>16&255)*.299+(n>>8&255)*.587+(n&255)*.114)/255});
ok('dark theme still dark', lum<0.2);
ok('no horizontal scroll', await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
ok('CTA still points at the app', await p.getAttribute('.big','href')==='./app.html');
await p.click('.toggle'); await p.waitForTimeout(400);
await p.click('.sw[data-v=romance]'); await p.waitForTimeout(900);
await p.evaluate(()=>document.querySelector('#sw').scrollIntoView({block:'center'})); await p.waitForTimeout(700);
await p.screenshot({path:'land-gen.png'});
console.log(`\nPASSED ${pass}  FAILED ${fail}`);
await br.close();
